# Generated by Django 2.2 on 2020-02-04 21:10

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confidentiality',
            name='personal_data_form',
            field=models.FileField(blank=True, help_text='Valid file formats: PDF, DOC, DOCX', null=True, upload_to=users.models.create_personal_data_form_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), users.models.FileSizeValidator]),
        ),
        migrations.AlterField(
            model_name='confidentiality',
            name='employee_number',
            field=models.CharField(blank=True, help_text='7-digit numerical value only', max_length=7, null=True, unique=True, validators=[users.models.NumericalValueValidator, django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
    ]
