# Generated by Django 2.2 on 2019-11-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidentiality',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confidentiality',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
