# Generated by Django 2.2 on 2019-10-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_number',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
