# Generated by Django 2.2 on 2019-12-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_multiple_same_type_degrees',
            field=models.BooleanField(default=False, help_text='Please indicate your degrees in Degree Details below if you have multiple same type degrees (MSc - Biology and MSc - Statistics).'),
        ),
    ]
