# Generated by Django 2.2 on 2020-01-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confidentiality',
            name='nationality',
            field=models.CharField(blank=True, choices=[('0', 'Domestic Student'), ('1', 'International Student')], max_length=1, null=True),
        ),
    ]
