# Generated by Django 2.2 on 2019-08-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
