# Generated by Django 2.2 on 2019-09-19 17:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidentiality',
            name='sin',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.create_sin_path),
        ),
        migrations.AlterField(
            model_name='confidentiality',
            name='study_permit',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.create_study_permit_path),
        ),
    ]
