# Generated by Django 2.2 on 2020-02-11 20:13

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200204_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidentiality',
            name='personal_data_form',
            field=models.FileField(blank=True, help_text='Valid file formats: PDF, DOC, DOCX', max_length=256, null=True, upload_to=users.models.create_personal_data_form_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), users.models.FileSizeValidator]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='uploaded',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=users.models.create_resume_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx']), users.models.FileSizeValidator]),
        ),
    ]
