# Generated by Django 2.2 on 2019-08-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190830_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidentiality',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confidentiality',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
