# Generated by Django 2.2 on 2020-02-13 16:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200204_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidentiality',
            name='employee_number',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, validators=[users.models.NumericalValueValidator, django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='confidentiality',
            name='personal_data_form',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=users.models.create_personal_data_form_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), users.models.FileSizeValidator]),
        ),
        migrations.AlterField(
            model_name='confidentiality',
            name='sin',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to=users.models.create_sin_path, validators=[users.models.FileSizeValidator]),
        ),
        migrations.AlterField(
            model_name='confidentiality',
            name='study_permit',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to=users.models.create_study_permit_path, validators=[users.models.FileSizeValidator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lfs_ta_training_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prior_employment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Program'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='program_others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='special_considerations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_number',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[users.models.NumericalValueValidator, django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ta_experience_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='training_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='uploaded',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=users.models.create_resume_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx']), users.models.FileSizeValidator]),
        ),
    ]
