# Generated by Django 2.2 on 2019-10-31 21:34

import datetime
import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191030_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='confidentiality',
            name='compression_agreement',
            field=models.FileField(blank=True, null=True, upload_to=users.models.create_compression_agreement_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='confidentiality',
            name='eform',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='confidentiality',
            name='pin',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='confidentiality',
            name='tasm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confidentiality',
            name='union_correspondence',
            field=models.FileField(blank=True, null=True, upload_to=users.models.create_union_correspondence_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='confidentiality',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='confidentiality',
            name='employee_number',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='confidentiality',
            name='updated_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
