# Generated by Django 2.2 on 2019-12-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_has_multiple_same_type_degrees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='has_multiple_same_type_degrees',
            field=models.BooleanField(default=False, help_text='Please indicate your degrees in Degree Details below if you have multiple same type degrees such as two Bachelors, two Masters or two PhDs (ex. MSc - Biology and MSc - Statistics).'),
        ),
    ]
