# Generated by Django 2.2 on 2019-09-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190906_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['pk']},
        ),
    ]
