# Generated by Django 2.2 on 2019-11-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191031_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidentiality',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
