# Generated by Django 2.2.10 on 2020-04-06 19:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0003_auto_20200213_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uploaded', models.ImageField(blank=True, max_length=256, null=True, upload_to=users.models.create_avatar_path, validators=[users.models.FileSizeValidator])),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
