# Generated by Django 2.2.19 on 2021-05-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_confidentiality_is_new_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='confidentiality',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
