# Generated by Django 2.2.27 on 2022-03-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_confidentiality_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_year',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=1, null=True),
        ),
    ]
