# Generated by Django 2.2.27 on 2022-04-04 23:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20220328_1534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alertemail',
            unique_together={('year', 'term', 'job_code', 'job_number', 'job_section', 'instructor', 'receiver_name', 'receiver_email')},
        ),
    ]
