# Generated by Django 5.2.7 on 2026-03-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_faculty_profile_has_graduated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_candidate_status',
            field=models.BooleanField(default=False),
        ),
    ]
