# Generated by Django 4.2.10 on 2024-02-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_graduated',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_year',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=2, null=True),
        ),
    ]
