# Generated by Django 4.2.10 on 2024-02-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_academic_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_ta_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_terms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
