# Generated by Django 4.2.10 on 2024-02-15 00:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_profilereminder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilereminder',
            unique_together={('user', 'session')},
        ),
    ]
