# Generated by Django 2.2 on 2019-09-05 16:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.CharField(choices=[('0', 'None'), ('1', 'Offered'), ('2', 'Accepted'), ('3', 'Declined')], default='0', max_length=1)),
                ('assigned_hours', models.FloatField(default=0.0)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('slug', models.SlugField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ['code', 'number', 'term', 'section'],
            },
        ),
        migrations.CreateModel(
            name='CourseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=256)),
                ('receiver', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=256)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrators.Term')),
            ],
            options={
                'ordering': ['-year', 'term'],
                'unique_together': {('year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('ta_hours', models.FloatField(default=0.0)),
                ('assigned_ta_hours', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.Course')),
                ('instructors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.Session')),
            ],
            options={
                'ordering': ['session', 'course'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='administrators.CourseCode'),
        ),
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrators.CourseNumber'),
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='administrators.CourseSection'),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrators.Term'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_approval', models.BooleanField()),
                ('how_qualified', models.CharField(choices=[('1', 'Not at all'), ('2', 'Marginally'), ('3', 'Somewhat'), ('4', 'Most'), ('5', 'Very')], max_length=1)),
                ('how_interested', models.CharField(choices=[('1', 'Not at all'), ('2', 'Marginally'), ('3', 'Somewhat'), ('4', 'Most'), ('5', 'Very')], max_length=1)),
                ('availability', models.BooleanField()),
                ('availability_note', models.TextField(blank=True, null=True)),
                ('classification', models.CharField(choices=[('0', 'None'), ('1', 'Type 1'), ('2', 'Type 2'), ('3', 'Type 3')], default='0', max_length=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('instructor_preference', models.CharField(choices=[('0', 'None'), ('1', 'No Preference'), ('2', 'Acceptable'), ('3', 'Requested'), ('4', 'Critical Requested')], default='0', max_length=1)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.Job')),
                ('status', models.ManyToManyField(to='administrators.ApplicationStatus')),
            ],
            options={
                'ordering': ['job', 'applicant'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'number', 'section', 'term')},
        ),
    ]
