# Generated by Django 2.2 on 2019-11-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecode',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='coursenumber',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'ordering': ['name']},
        ),
    ]
