# Generated by Django 2.2 on 2019-08-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_ta_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
