# Generated by Django 2.2 on 2020-02-04 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_declined_reassigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term',
            name='by_month',
            field=models.IntegerField(default=4, help_text='Minimun value: 1, Maximum Value: 12', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='term',
            name='max_hours',
            field=models.IntegerField(default=192, help_text='Minimun value: 0, Maximum Value: 4000', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='how_interested',
            field=models.CharField(choices=[('0', 'Select'), ('1', 'Not at all'), ('2', 'Marginally'), ('3', 'Somewhat'), ('4', 'Very'), ('5', 'Most')], max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='how_qualified',
            field=models.CharField(choices=[('0', 'Select'), ('1', 'Not at all'), ('2', 'Marginally'), ('3', 'Somewhat'), ('4', 'Very'), ('5', 'Most')], max_length=1),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='assigned_hours',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(4000)]),
        ),
        migrations.AlterField(
            model_name='coursecode',
            name='name',
            field=models.CharField(help_text='Maximum characters: 5', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='coursenumber',
            name='name',
            field=models.CharField(help_text='Maximum characters: 5', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='name',
            field=models.CharField(help_text='Maximum characters: 5', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='code',
            field=models.CharField(help_text='This field is unique and maximum characters: 20', max_length=20, unique=True),
        ),
    ]
