# Generated by Django 2.2 on 2019-10-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0002_auto_20191008_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='assigned',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Offered'), ('2', 'Accepted'), ('3', 'Declined'), ('4', 'Cancelled')], default='0', max_length=1),
        ),
    ]
