# Generated by Django 2.2 on 2019-12-11 18:56

import administrators.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0002_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDocuments',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administrators.Application')),
                ('pin', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('tasm', models.BooleanField(default=False)),
                ('eform', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('speed_chart', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('union_correspondence', models.FileField(blank=True, null=True, upload_to=administrators.models.create_union_correspondence_path)),
                ('compression_agreement', models.FileField(blank=True, null=True, upload_to=administrators.models.create_compression_agreement_path)),
                ('processing_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
