# Generated by Django 2.2 on 2020-02-12 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0002_auto_20200204_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='job_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='course_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admindocuments',
            name='eform',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='admindocuments',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='admindocuments',
            name='processing_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admindocuments',
            name='speed_chart',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='admindocuments',
            name='tasm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='supervisor_approval',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='classification',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='coursecode',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='coursenumber',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='assigned_ta_hours',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000)]),
        ),
        migrations.AlterField(
            model_name='term',
            name='by_month',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='term',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='max_hours',
            field=models.IntegerField(default=192, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000)]),
        ),
    ]
