# Generated by Django 2.2 on 2019-09-05 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0003_auto_20190905_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['created_at']},
        ),
    ]
