# Generated by Django 2.2.9 on 2020-04-01 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0004_landingpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='accumulated_ta_hours',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000)]),
        ),
    ]
