# Generated by Django 2.2.9 on 2020-03-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0004_landingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
