# Generated by Django 2.2 on 2019-09-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0004_auto_20190905_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-created_at']},
        ),
    ]
