# Generated by Django 2.2 on 2019-09-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0005_auto_20190905_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-pk']},
        ),
    ]
