# Generated by Django 2.2.10 on 2020-04-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0005_auto_20200401_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='has_contract_read',
            field=models.BooleanField(default=False),
        ),
    ]
