# Generated by Django 2.2.10 on 2020-05-22 19:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrators', '0006_applicationstatus_has_contract_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindocuments',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='admindocuments',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='AdminDocumentsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.AdminDocuments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
