# Generated by Django 2.2 on 2019-09-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0006_auto_20190905_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecode',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='coursenumber',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['code']},
        ),
    ]
