# Generated by Django 2.2.10 on 2020-05-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0007_auto_20200522_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindocumentsuser',
            name='user',
            field=models.CharField(max_length=256),
        ),
    ]
