# Generated by Django 2.2.13 on 2021-01-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0008_auto_20200522_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindocuments',
            name='worktag',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
