# Generated by Django 2.2 on 2019-09-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0008_auto_20190906_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstatus',
            name='updated_at',
        ),
    ]
