# Generated by Django 2.2.19 on 2021-05-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0009_admindocuments_worktag'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindocuments',
            name='processed',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='admindocuments',
            name='worktag',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
