# Generated by Django 2.2.19 on 2021-07-29 16:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0010_auto_20210514_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.Application')),
            ],
        ),
    ]
