# Generated by Django 4.2.10 on 2024-02-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0013_alter_admindocumentsuser_id_alter_adminemail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sta_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
