# Generated by Django 4.2.13 on 2024-07-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0014_application_sta_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorktagHours',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administrators.application')),
                ('program_hours', models.JSONField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterField(
            model_name='admindocuments',
            name='worktag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
