# Generated by Django 4.2.13 on 2024-08-09 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0015_admindocuments_position_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorktagHours',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administrators.application')),
                ('job_id', models.BigIntegerField()),
                ('program_hours', models.JSONField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
