# Generated by Django 2.2 on 2019-08-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='instructor_preference',
            field=models.CharField(choices=[('0', 'None'), ('1', 'No Preference'), ('2', 'Acceptable'), ('3', 'Requested'), ('4', 'Critical Requested')], default='0', max_length=1),
        ),
    ]
