# Generated by Django 2.2 on 2019-08-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_active',
        ),
        migrations.AddField(
            model_name='session',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
