# Generated by Django 2.2 on 2019-08-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['job', 'applicant']},
        ),
    ]
